// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQC4PcEg0MGySGyLpg26Nx-sbHVgcx7lw',
    appId: '1:925167052954:web:698b7df10378b582905723',
    messagingSenderId: '925167052954',
    projectId: 'carsync-mi',
    authDomain: 'carsync-mi.firebaseapp.com',
    databaseURL: 'https://carsync-mi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carsync-mi.firebasestorage.app',
    measurementId: 'G-1G4G4DBEHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWU5m-Ky4Rta3TA2-MKE9VPW77x2HYAEg',
    appId: '1:925167052954:android:66201f31ea7d5c06905723',
    messagingSenderId: '925167052954',
    projectId: 'carsync-mi',
    databaseURL: 'https://carsync-mi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carsync-mi.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCAMhBVlNBghAA9NjYehsFRCKnK6ecLmnM',
    appId: '1:925167052954:ios:120422eab0bd7096905723',
    messagingSenderId: '925167052954',
    projectId: 'carsync-mi',
    databaseURL: 'https://carsync-mi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carsync-mi.firebasestorage.app',
    androidClientId: '925167052954-668rdebt40ifuhm8f78bpkg778c8kpsa.apps.googleusercontent.com',
    iosClientId: '925167052954-pugptg2sg2k3e88bhkq04ht13aeij09p.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCAMhBVlNBghAA9NjYehsFRCKnK6ecLmnM',
    appId: '1:925167052954:ios:120422eab0bd7096905723',
    messagingSenderId: '925167052954',
    projectId: 'carsync-mi',
    databaseURL: 'https://carsync-mi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carsync-mi.firebasestorage.app',
    androidClientId: '925167052954-668rdebt40ifuhm8f78bpkg778c8kpsa.apps.googleusercontent.com',
    iosClientId: '925167052954-pugptg2sg2k3e88bhkq04ht13aeij09p.apps.googleusercontent.com',
    iosBundleId: 'com.example.carSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQC4PcEg0MGySGyLpg26Nx-sbHVgcx7lw',
    appId: '1:925167052954:web:7ed74e1ad1189d8e905723',
    messagingSenderId: '925167052954',
    projectId: 'carsync-mi',
    authDomain: 'carsync-mi.firebaseapp.com',
    databaseURL: 'https://carsync-mi-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'carsync-mi.firebasestorage.app',
    measurementId: 'G-7X25NEY197',
  );

}